hostname = "kapacitor"

[data]
  dir = "/var/lib/kapacitor"

[storage]
  boltdb = "/var/lib/kapacitor/kapacitor.db"

[http]
  bind-address = ":9094"
  auth-enabled = false
  log-enabled = true
  write-tracing = false

[replay]
  dir = "/var/lib/kapacitor/replay"

[task]
  dir = "/var/lib/kapacitor/tasks"
  snapshot-interval = "1m0s"

[[influxdb]]
  enabled = true
  name = "influxdb"
  default = true
  urls = ["http://localhost:8086"]
  timeout = "0"
  insecure-skip-verify = false
  disable-subscriptions = false
  subscription-protocol = "http"
  subscription-mode = "cluster"
