[agent]
  interval = "5s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  flush_interval = "5s"
  flush_jitter = "0s"
  precision = ""
  hostname = ""
  omit_hostname = true

[[inputs.kafka_consumer]]
  brokers = ["kafka:9092"]
  topics = ["tsms-metrics"]
  consumer_group = "telegraf-tsms"
  data_format = "json_v2"

  [[inputs.kafka_consumer.json_v2]]
    measurement_name = "metrics"
    timestamp_path = "time"
    timestamp_format = "2006-01-02T15:04:05Z07:00"

    [[inputs.kafka_consumer.json_v2.field]]
      path = "value"
      type = "float"

    [[inputs.kafka_consumer.json_v2.field]]
      path = "is_injected_anomaly"
      type = "bool"

    [[inputs.kafka_consumer.json_v2.tag]]
      path = "sensor_id"

    [[inputs.kafka_consumer.json_v2.tag]]
      path = "signal_type"

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "$INFLUX_TOKEN"
  organization = "$INFLUX_ORG"
  bucket = "$INFLUX_BUCKET"
